version: "2"
run:
  build-tags:
    - integration
  tests: true
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard # As much as I would like to use this, it is completely unmanageable.
    - exhaustruct # This lib is usually pointless.
  settings:
    cyclop:
      max-complexity: 30
      package-average: 5
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 15
    godot:
      capital: true
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    misspell:
      locale: UK
    nlreturn:
      block-size: 2
    staticcheck:
      checks:
        - all
    unparam:
      check-exported: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - (context.Context).Err()
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - errcheck
          - gochecknoinits # I'm OK with inits for tests.
          - gocritic # Some of these are actually correct and should not be ignored / changed.
          - gosec # Some errors I tried to fix, others (such as forcing crypto/rand) make no sense.
          - testifylint # I tried to remove a few of them.
          - wrapcheck
        path: _test\.go
      - linters:
          - lll
          - revive
          - staticcheck
        path: mocks
      - linters:
          - dupword
        path: docs.go
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - model
      - tmp
      - bin
      - scripts
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/blokur)
        - localmodule
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - model
      - tmp
      - bin
      - scripts
      - third_party$
      - builtin$
      - examples$
