// Code generated by "stringer -type=AckType,DeliveryMode -output=constants_string.go"; DO NOT EDIT.

package harego

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AckTypeAck-0]
	_ = x[AckTypeNack-1]
	_ = x[AckTypeReject-2]
	_ = x[AckTypeRequeue-3]
	_ = x[_invalidAckType-4]
}

const _AckType_name = "AckTypeAckAckTypeNackAckTypeRejectAckTypeRequeue_invalidAckType"

var _AckType_index = [...]uint8{0, 10, 21, 34, 48, 63}

func (i AckType) String() string {
	if i < 0 || i >= AckType(len(_AckType_index)-1) {
		return "AckType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AckType_name[_AckType_index[i]:_AckType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeliveryModeTransient-1]
	_ = x[DeliveryModePersistent-2]
}

const _DeliveryMode_name = "DeliveryModeTransientDeliveryModePersistent"

var _DeliveryMode_index = [...]uint8{0, 21, 43}

func (i DeliveryMode) String() string {
	i -= 1
	if i >= DeliveryMode(len(_DeliveryMode_index)-1) {
		return "DeliveryMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DeliveryMode_name[_DeliveryMode_index[i]:_DeliveryMode_index[i+1]]
}
