name: Continues Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*
      - refactor/*
      - chore/*
      - feat/*
      - fix/*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/blokur
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Granting Private Modules Access
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_USER: bkrps
          GOPRIVATE: github.com/blokur
        run: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - uses: satackey/action-docker-layer-caching@v0
        continue-on-error: true

      - name: Running Tests
        run: make ci_tests

  lint:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/blokur
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Granting Private Modules Access
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_USER: bkrps
          GOPRIVATE: github.com/blokur
        run: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout 5m0s
