name: Continues Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*
      - refactor/*
      - chore/*

jobs:
  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go: [ ">=1.25.0" ]
    name: Test with Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - uses: satackey/action-docker-layer-caching@v0
        continue-on-error: true

      - name: Tidy modules
        run: go mod tidy

      - name: Running Tests
        run: make ci_tests

  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go: [ ">=1.25.0" ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Tidy modules
        run: go mod tidy

      - name: Check for go vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: WriteGoList
        run: go list -json -deps > go.list

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go: [ ">=1.25.0" ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Tidy modules
        run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 5m0s

      - id: govulncheck
        uses: golang/govulncheck-action@v1
