name: Continues Integration

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*
      - refactor/*
      - chore/*

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.20.x", "1.21.x", "1.22.x"]
    name: Test with Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Tidy modules
        run: go mod tidy

      - name: Running Tests
        run: make ci_tests

  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.20.9", "1.21.x", "1.22.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Tidy modules
        run: go mod tidy

      - name: Check for go vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: WriteGoList
        run: go list -json -deps > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.20.x", "1.21.x", "1.22.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Tidy modules
        run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 5m0s
